baseURL = "https://kenji.blog/"
languageCode = "ja"
DefaultContentLanguage = "ja"
title = "ç§ã®ãƒ¡ãƒ¢å¸³"
theme = "PaperMod"

[params.homeInfoParams]
	Title = "Hi there ğŸ‘‹ ğŸµ"
	Content = "My name is kenji, this is me thinking about life and software, discovering old lessons and learning new stuff."
