baseURL = "https://kenji.blog/"
languageCode = "ja"
DefaultContentLanguage = "ja"
title = "kenji.blog"
theme = "PaperMod"
googleAnalytics = "UA-60997585-5"

[params]
    dateFormat= "2006.01.02"
    images = ["twitter_card.jpg"]
    ShowShareButtons = true

[params.label]
    text = "ğŸ  Home"

[params.homeInfoParams]
    Title = "Hello world! ğŸ˜Š"
    Content = "ã“ã‚“ã«ã¡ã¯ä¸–ç•Œã€‚æ™®æ®µè€ƒãˆãŸã“ã¨ã‚„æŠ€è¡“çš„ãªå°è©±ã‚’çŸ­ã‚ã®è¨˜äº‹ã«ãƒ¡ãƒ¢ä»£ã‚ã‚Šã§æŠ•ç¨¿ã—ã¦ã„ãã¾ã™ã€‚PaperModã¨ã„ã†ãƒ†ãƒ¼ãƒã‚’ä½¿ã£ã¦ã„ã¾ã™ã€‚"

[[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/kenjinote"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/kenjinote"

[[params.socialIcons]]
    name = "link"
    url = "https://hack.jp"

[[params.socialIcons]]
    name = "email"
    url = "mailto:kenji256@gmai.com"

[[params.socialIcons]]
    name = "KoFi"
    url = "https://ko-fi.com/kenjinote"

[[params.socialIcons]]
    name = "Rss"
    url = "index.xml"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

#[[menu.main]]
#    name = "About"
#    url = "/about"
#    weight = 1

#[[menu.main]]
#    name = "Search"
#    url = "/Search"
#    weight = 2
