baseURL = "https://kenji.blog/"
languageCode = "ja"
DefaultContentLanguage = "ja"
timeZone = "Asia/Tokyo"
title = "kenji.blog"
theme = "PaperMod"
googleAnalytics = "GT-5R8HJJC"
pygmentsUseClasses = true

[markup.goldmark.renderer]
    unsafe = true

[params]
    dateFormat= "2006.01.02"
    images = ["twitter_card.jpg"]
    ShowShareButtons = true
    ShowBreadCrumbs = false

[params.homeInfoParams]
    Title = "グッドバイ"
    Content = "グッドバイは、kenji が運営する雑記ブログです。特にテーマを決めず普段考えたこと、気になって調べたこと等をつらつらと書き連ねていきます。"

[[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/kenjinote"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/kenjinote"

[[params.socialIcons]]
    name = "link"
    url = "https://hack.jp"

[[params.socialIcons]]
    name = "email"
    url = "mailto:kenji256@gmai.com"

[[params.socialIcons]]
    name = "KoFi"
    url = "https://ko-fi.com/kenjinote"

[[params.socialIcons]]
    name = "Rss"
    url = "index.xml"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[[menu.main]]
    name = "Search"
    url = "/search"
    weight = 1

[[menu.main]]
    name = "Archives"
    url = "/archives"
    weight = 2

[[menu.main]]
    name = "@Author"
    url = "https://kenji.jp/"
    weight = 3
